export enum ErrorCode {
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  GATEWAY_NOT_FOUND = 'GATEWAY_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  NO_GATEWAY_AVAILABLE = 'NO_GATEWAY_AVAILABLE',
  TRANSACTION_ALREADY_REVERSED = 'TRANSACTION_ALREADY_REVERSED',
  INVALID_TRANSACTION_STATE = 'INVALID_TRANSACTION_STATE',
  GATEWAY_REFUND_FAILED = 'GATEWAY_REFUND_FAILED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}
